version: "3"
services:
  mysql57:
    image: "mysql:8.0"
    container_name: "deebee_mysql57"
    ports:
      - "${MYSQL57_FORWARD_PORT:-3357}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-secret}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "mysql57:/var/lib/mysql"
      - "./config/:/etc/mysql/conf.d"
    networks:
      - network

  mysql80:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    container_name: "deebee_mysql80"
    ports:
      - "${MYSQL80_FORWARD_PORT:-3380}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-secret}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "mysql80:/var/lib/mysql"
      - "./config/:/etc/mysql/conf.d"
    networks:
      - network

  redis:
    image: "redis:alpine"
    container_name: "deebee_memcached"
    ports:
      - "${REDIS_FORWARD_PORT:-6397}:6379"
    volumes:
      - "redis:/data"
    networks:
      - network

  memcached:
    image: "memcached:alpine"
    container_name: "deebee_redis"
    ports:
      - "${MEMCACHED_FORWARD_PORT:-11222}:11211"
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  mysql80:
    driver: local
  mysql57:
    driver: local
  redis:
    driver: local